// Generates the man page, shell completions, and the docs reference tables from
// src/help.ts so the flag list has a single source of truth. Run via
// `npm run gen:docs` (wired into `npm run build`). The generated files under
// man/ and completions/, and the marked table regions in docs/, are committed —
// do not hand-edit them.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ACTIONS, OPTIONS, SUBCOMMANDS, TAGLINE, DOCS_URL, type Flag } from "../src/help.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const GENERATED = "generated by scripts/gen-docs.ts — do not edit by hand";

/** Read a completion template and stamp it with the generated banner. */
function template(name: string, banner: string): string {
  return readFileSync(join(here, "completion", name), "utf8").replace(
    "# GENERATED_BANNER",
    `# ${banner}`
  );
}

// --- man page (roff) -------------------------------------------------------

/** Escape backslashes and hyphens so roff renders them literally. */
function roff(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/-/g, "\\-");
}

function manEntry(f: Flag): string {
  return `.TP\n.BR \\-${f.short} ", " \\-\\-${f.long}\n${roff(f.desc)}`;
}

const man =
  `.\\" ${GENERATED}\n` +
  `.TH GIT\\-FI 1 "" "" "Git Extensions"\n` +
  `.SH NAME\n` +
  `git\\-fi \\- maintain a temporary integration branch for early conflict detection\n` +
  `.SH SYNOPSIS\n` +
  `.B git fi\n` +
  `[options] [<branch>...]\n` +
  `.SH DESCRIPTION\n` +
  `${roff(TAGLINE)}\n` +
  `.PP\n` +
  `With no action, lists the branches currently merged into \\fBfi\\fR.\n` +
  `.SH ACTIONS\n` +
  ACTIONS.map(manEntry).join("\n") + "\n" +
  `.SH OPTIONS\n` +
  OPTIONS.map(manEntry).join("\n") + "\n" +
  `.SH COMMANDS\n` +
  SUBCOMMANDS.map((c) => `.TP\n.B ${roff(c.usage)}\n${roff(c.desc)}`).join("\n") + "\n" +
  `.SH SEE ALSO\n` +
  `Full documentation: ${roff(DOCS_URL)}\n`;

// --- shell completions -----------------------------------------------------
//
// The completion logic lives in real shell files under scripts/completion/;
// here we only inject the flag list derived from the metadata above. Branch
// completion is action-aware (see the templates for the details).

const longFlags = [...ACTIONS, ...OPTIONS].map((f) => `--${f.long}`).join(" ");

// The git-completion-format body (defines _git_fi) is shared by two outputs:
// completions/git-fi.bash, sourced by bash, and completions/_git_fi, autoloaded
// from the zsh fpath when git's own completion wrapper — not zsh's built-in
// _git — dispatches `git fi` (to _git_fi under ksh emulation). It uses git's
// portable $cur/$words, so the same function runs in both shells.
const gitNativeBody = readFileSync(
  join(here, "completion", "git-fi.bash.tmpl"),
  "utf8"
).replaceAll("@@LONG_FLAGS@@", longFlags);

const bash =
  `# ${GENERATED}\n` +
  `# git-completion-format completion for \`git fi\` (defines _git_fi). Load it in\n` +
  `# bash (needs git's bash completion) with:\n` +
  `#   source <(git fi install-completions bash)\n` +
  `# The same function serves zsh under git's own completion wrapper; that copy\n` +
  `# ships as completions/_git_fi.\n` +
  gitNativeBody;

// The #autoload tag must be the first line so compinit autoloads _git_fi.
const gitNativeZsh =
  `#autoload\n` +
  `# ${GENERATED}\n` +
  `# zsh fpath copy of the git-completion-format _git_fi, for git's own\n` +
  `# completion wrapper (git dispatches \`git fi\` to _git_fi under ksh emulation).\n` +
  `# For zsh's built-in _git, see completions/_git-fi instead.\n` +
  gitNativeBody;

const zshSpec = (f: Flag): string =>
  `    '(-${f.short} --${f.long})'{-${f.short},--${f.long}}'[${f.desc}]'`;
const argSpecs = [...ACTIONS, ...OPTIONS].map((f) => zshSpec(f) + " \\").join("\n");
const zsh = template("git-fi.zsh.tmpl", GENERATED).replace("@@ARG_SPECS@@", argSpecs);

// --- docs reference tables -------------------------------------------------
//
// The prose docs under docs/ are hand-written, but their flag/action reference
// tables duplicate the metadata above. Stamp those tables in place between
// `<!-- BEGIN GENERATED: <name> -->` / `<!-- END GENERATED: <name> -->` markers
// so a new flag can't go missing from the docs the way it can't from the man
// page. Everything outside the markers is left untouched.

function mdTable(flags: Flag[]): string {
  const rows = flags.map((f) => `| \`-${f.short}\` | \`--${f.long}\` | ${f.desc} |`);
  return ["| Flag | Long | Description |", "|------|------|-------------|", ...rows].join("\n");
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Replace the body between the named BEGIN/END markers in a docs file. */
function injectTable(relPath: string, name: string, body: string): void {
  const file = join(root, relPath);
  const begin = `<!-- BEGIN GENERATED: ${name} -->`;
  const end = `<!-- END GENERATED: ${name} -->`;
  const region = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`);
  const src = readFileSync(file, "utf8");
  if (!region.test(src)) {
    throw new Error(`generated markers "${name}" not found in ${relPath} — add them or fix the name`);
  }
  const replacement = `${begin}\n<!-- ${GENERATED} -->\n\n${body}\n\n${end}`;
  writeFileSync(file, src.replace(region, replacement));
}

// --- write -----------------------------------------------------------------

mkdirSync(join(root, "man"), { recursive: true });
mkdirSync(join(root, "completions"), { recursive: true });
writeFileSync(join(root, "man", "git-fi.1"), man);
writeFileSync(join(root, "completions", "git-fi.bash"), bash);
writeFileSync(join(root, "completions", "_git_fi"), gitNativeZsh);
writeFileSync(join(root, "completions", "_git-fi"), zsh);

injectTable("docs/commands.md", "actions", mdTable(ACTIONS));
injectTable("docs/commands.md", "options", mdTable(OPTIONS));

process.stdout.write(
  "Generated man/git-fi.1, completions/git-fi.bash, completions/_git_fi, completions/_git-fi, docs/commands.md tables\n"
);
