// Generates the man page and shell completions from src/help.ts so the flag
// list has a single source of truth. Run via `npm run gen:docs` (wired into
// `npm run build`). The generated files under man/ and completions/ are
// committed — do not hand-edit them.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ACTIONS, OPTIONS, SUBCOMMANDS, TAGLINE, DOCS_URL, type Flag } from "../src/help.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const GENERATED = "generated by scripts/gen-docs.ts — do not edit by hand";

/** Read a completion template and stamp it with the generated banner. */
function template(name: string, banner: string): string {
  return readFileSync(join(here, "completion", name), "utf8").replace(
    "# GENERATED_BANNER",
    `# ${banner}`
  );
}

// --- man page (roff) -------------------------------------------------------

/** Escape backslashes and hyphens so roff renders them literally. */
function roff(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/-/g, "\\-");
}

function manEntry(f: Flag): string {
  return `.TP\n.BR \\-${f.short} ", " \\-\\-${f.long}\n${roff(f.desc)}`;
}

const man =
  `.\\" ${GENERATED}\n` +
  `.TH GIT\\-FI 1 "" "" "Git Extensions"\n` +
  `.SH NAME\n` +
  `git\\-fi \\- maintain a temporary integration branch for early conflict detection\n` +
  `.SH SYNOPSIS\n` +
  `.B git fi\n` +
  `[options] [<branch>...]\n` +
  `.SH DESCRIPTION\n` +
  `${roff(TAGLINE)}\n` +
  `.PP\n` +
  `With no action, lists the branches currently merged into \\fBfi\\fR.\n` +
  `.SH ACTIONS\n` +
  ACTIONS.map(manEntry).join("\n") + "\n" +
  `.SH OPTIONS\n` +
  OPTIONS.map(manEntry).join("\n") + "\n" +
  `.SH COMMANDS\n` +
  SUBCOMMANDS.map((c) => `.TP\n.B ${roff(c.usage)}\n${roff(c.desc)}`).join("\n") + "\n" +
  `.SH SEE ALSO\n` +
  `Full documentation: ${roff(DOCS_URL)}\n`;

// --- shell completions -----------------------------------------------------
//
// The completion logic lives in real shell files under scripts/completion/;
// here we only inject the flag list derived from the metadata above. Branch
// completion is action-aware (see the templates for the details).

const longFlags = [...ACTIONS, ...OPTIONS].map((f) => `--${f.long}`).join(" ");
const bash = template("git-fi.bash.tmpl", GENERATED).replace(
  "@@LONG_FLAGS@@",
  longFlags
);

const zshSpec = (f: Flag): string =>
  `    '(-${f.short} --${f.long})'{-${f.short},--${f.long}}'[${f.desc}]'`;
const argSpecs = [...ACTIONS, ...OPTIONS].map((f) => zshSpec(f) + " \\").join("\n");
const zsh = template("git-fi.zsh.tmpl", GENERATED).replace("@@ARG_SPECS@@", argSpecs);

// --- write -----------------------------------------------------------------

mkdirSync(join(root, "man"), { recursive: true });
mkdirSync(join(root, "completions"), { recursive: true });
writeFileSync(join(root, "man", "git-fi.1"), man);
writeFileSync(join(root, "completions", "git-fi.bash"), bash);
writeFileSync(join(root, "completions", "_git-fi"), zsh);

process.stdout.write("Generated man/git-fi.1, completions/git-fi.bash, completions/_git-fi\n");
